### ISSUE TITLE
Encountering version conflict when attempting to run bin/buildout

### ISSUE THREAD

**Issue by sgambino** [cewing/training.python_web#85]
I've attempted to run the bin/buildout to be able to generate the documentation. Included here is the standard out/standard error with a few annotations explaining what I did in trying to get to a complete and successful setup. I use the word "complete" here because I actually got the point where I could build the html as noted below. One thing to note is that as I tried this several times. I finally tried it in a virtual environment and before the FIRST PASS I did a "pip install --upgrade setuptools" which fetched setuptools 0.9.8    Prior to this it was from my system packages it was using  setuptools 0.6c11.

```
#
# FIRST PASS: bin/buildout
#

While:
  Installing.
  Loading extensions.
Error: Buildout now includes 'buildout-versions' (and part of the older 'buildout.dumppickedversions').
Remove the extension from your configuration and look at the 'show-picked-versions' option in buildout's documentation.

#
# SECOND PASS: bin/buildout after commenting out "buildout.dumppickedversions"
#

Getting distribution for 'zc.buildout==1.5.2'.
Got zc.buildout 1.5.2.
Getting distribution for 'setuptools==0.6c12dev-r88846'.
While:
  Installing.
  Checking for upgrades.
  Getting distribution for 'setuptools==0.6c12dev-r88846'.
Error: Couldn't find a distribution for 'setuptools==0.6c12dev-r88846'.


#
# THIRD PASS: bin/buildout after commenting out setuptools==0.6c12dev-r88846
#
# Here is where I encountered a Traceback. See Traceback below.
#
# Note that having gotten this far in the buildout, I am able to
# successfully build the html. That is, I can run bin/sphinx successfully.
# However, I have no bin/build_s5 directory to be able to attempt building
# the slides.
#


Upgraded:
  zc.buildout version 1.5.2;
restarting.
Generated script '/Users/sgambino/build_doc/training.python_web/bin/buildout'.
Getting distribution for 'collective.recipe.sphinxbuilder==0.7.1'.
warning: no previously-included files matching '*pyc' found anywhere in distribution
Got collective.recipe.sphinxbuilder 0.7.1.
Getting distribution for 'Sphinx==1.1.3'.
Got Sphinx 1.1.3.
Getting distribution for 'docutils==0.9.1'.
warning: no files found matching 'MANIFEST'
warning: no files found matching '*' under directory 'extras'
warning: no previously-included files matching '.cvsignore' found under directory '*'
warning: no previously-included files matching '*.pyc' found under directory '*'
warning: no previously-included files matching '*~' found under directory '*'
warning: no previously-included files matching '.DS_Store' found under directory '*'
zip_safe flag not set; analyzing archive contents...
docutils.parsers.rst.directives.misc: module references __file__
docutils.writers.html4css1.__init__: module references __file__
docutils.writers.latex2e.__init__: module references __file__
docutils.writers.odf_odt.__init__: module references __file__
docutils.writers.pep_html.__init__: module references __file__
docutils.writers.s5_html.__init__: module references __file__
Got docutils 0.9.1.
Getting distribution for 'zc.recipe.egg==1.3.2'.
Got zc.recipe.egg 1.3.2.
Getting distribution for 'Jinja2==2.6'.
warning: no previously-included files matching '*' found under directory 'docs/_build'
warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
Got Jinja2 2.6.
Getting distribution for 'Pygments==1.5'.
Got Pygments 1.5.
Getting distribution for 'rjm.recipe.venv==0.8'.
Got rjm.recipe.venv 0.8.
Getting distribution for 'virtualenv==1.8.2'.
warning: no previously-included files matching '*' found under directory 'docs/_templates'
warning: no previously-included files matching '*' found under directory 'docs/_build'
Got virtualenv 1.8.2.
Getting distribution for 'gp.recipe.pip'.
Got gp.recipe.pip 0.5.3.
Getting distribution for 'distribute==0.6.30'.
Got distribute 0.6.30.
Getting distribution for 'collective.recipe.template[genshi]==1.9'.
Got collective.recipe.template 1.9.
Getting distribution for 'Genshi==0.6'.
warning: no previously-included files found matching 'doc/2000ft.graffle'
warning: no previously-included files matching '*' found under directory 'doc/logo.lineform'
zip_safe flag not set; analyzing archive contents...
Got Genshi 0.6.
Getting distribution for 'collective.recipe.cmd==0.5'.
Got collective.recipe.cmd 0.5.
Installing sphinx.
collective.recipe.sphinxbuilder: writing MAKEFILE..
collective.recipe.sphinxbuilder: writing BATCHFILE..
collective.recipe.sphinxbuilder: writing custom sphinx-builder script..
Getting distribution for 'roman==1.4.0'.
Got roman 1.4.0.
Generated script '/Users/sgambino/build_doc/training.python_web/bin/sphinx-quickstart'.
Generated script '/Users/sgambino/build_doc/training.python_web/bin/sphinx-build'.
Installing venv.
Using real prefix '/System/Library/Frameworks/Python.framework/Versions/2.7'
New python executable in /Users/sgambino/build_doc/training.python_web/bin/python
Installing setuptools............done.
Installing pip...............done.
Traceback (most recent call last):
  File "/Users/sgambino/build_doc/training.python_web/bootstrap.py", line 59, in <module>
    ws.require('zc.buildout')
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 666, in require
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 569, in resolve
pkg_resources.VersionConflict: (setuptools 0.6c11 (/Users/sgambino/build_doc/training.python_web/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg), Requirement.parse('setuptools>=0.7'))
Updating sphinx.
collective.recipe.sphinxbuilder: writing MAKEFILE..
collective.recipe.sphinxbuilder: writing BATCHFILE..
collective.recipe.sphinxbuilder: writing custom sphinx-builder script..
Installing venv.
Traceback (most recent call last):
  File "/Users/sgambino/build_doc/training.python_web/bootstrap.py", line 59, in <module>
    ws.require('zc.buildout')
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 666, in require
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 569, in resolve
pkg_resources.VersionConflict: (setuptools 0.6c11 (/Users/sgambino/build_doc/training.python_web/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg), Requirement.parse('setuptools>=0.7'))
Updating sphinx.
collective.recipe.sphinxbuilder: writing MAKEFILE..
collective.recipe.sphinxbuilder: writing BATCHFILE..
collective.recipe.sphinxbuilder: writing custom sphinx-builder script..
Installing venv.
Traceback (most recent call last):
  File "/Users/sgambino/build_doc/training.python_web/bootstrap.py", line 59, in <module>
    ws.require('zc.buildout')
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 666, in require
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 569, in resolve
pkg_resources.VersionConflict: (setuptools 0.6c11 (/Users/sgambino/build_doc/training.python_web/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg), Requirement.parse('setuptools>=0.7'))
Updating sphinx.
collective.recipe.sphinxbuilder: writing MAKEFILE..
collective.recipe.sphinxbuilder: writing BATCHFILE..
collective.recipe.sphinxbuilder: writing custom sphinx-builder script..
Installing venv.
Traceback (most recent call last):
  File "/Users/sgambino/build_doc/training.python_web/bootstrap.py", line 59, in <module>
    ws.require('zc.buildout')
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 666, in require
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 569, in resolve
pkg_resources.VersionConflict: (setuptools 0.6c11 (/Users/sgambino/build_doc/training.python_web/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg), Requirement.parse('setuptools>=0.7'))
Traceback (most recent call last):
  File "/Users/sgambino/build_doc/training.python_web/bin/buildout", line 12, in <module>
    sys.exit(zc.buildout.buildout.main())
  File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/buildout.py", line 1805, in main
Traceback (most recent call last):
  File "bin/buildout", line 12, in <module>
    sys.exit(zc.buildout.buildout.main())
  File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-2.2.0-py2.7.egg/zc/buildout/buildout.py", line 1942, in main
    getattr(buildout, command)(args)
  File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/buildout.py", line 433, in install
Traceback (most recent call last):
  File "/Users/sgambino/build_doc/training.python_web/bin/buildout", line 12, in <module>
Traceback (most recent call last):
      File "/Users/sgambino/build_doc/training.python_web/bin/buildout", line 12, in <module>
Traceback (most recent call last):
  File "/Users/sgambino/build_doc/training.python_web/bin/buildout", line 12, in <module>
sys.exit(zc.buildout.buildout.main())
Traceback (most recent call last):
      File "bin/buildout", line 12, in <module>
sys.exit(zc.buildout.buildout.main())
  File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/buildout.py", line 1805, in main
  File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/buildout.py", line 1805, in main
    sys.exit(zc.buildout.buildout.main())
    sys.exit(zc.buildout.buildout.main())
  File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/buildout.py", line 1805, in main
      File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/buildout.py", line 1805, in main
getattr(buildout, command)(args)
      File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-2.2.0-py2.7.egg/zc/buildout/buildout.py", line 471, in install
self._maybe_upgrade()
  File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/buildout.py", line 864, in _maybe_upgrade
    self._maybe_upgrade()
  File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-2.2.0-py2.7.egg/zc/buildout/buildout.py", line 961, in _maybe_upgrade
    prefer_final=not self.accept_buildout_test_releases,
  File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/easy_install.py", line 1090, in install
        getattr(buildout, command)(args)
sys.exit(subprocess.call(args))
    getattr(buildout, command)(args)
  File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/buildout.py", line 584, in install
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 486, in call
  File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/buildout.py", line 584, in install
    getattr(buildout, command)(args)
  File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/buildout.py", line 584, in install
    getattr(buildout, command)(args)
  File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/buildout.py", line 584, in install
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1243, in wait
    installed_files = self[part]._call(recipe.install)
      File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/buildout.py", line 1297, in _call
installed_files = self[part]._call(recipe.install)
      File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/buildout.py", line 1297, in _call
return installer.install(specs, working_set)
  File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/easy_install.py", line 896, in install
    installed_files = self[part]._call(recipe.install)
  File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/buildout.py", line 1297, in _call
    installed_files = self[part]._call(recipe.install)
  File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/buildout.py", line 1297, in _call
    for dist in self._get_dist(requirement, ws, self._always_unzip):
      File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/easy_install.py", line 723, in _get_dist
pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 471, in _eintr_retry_call
    return f()
  File "/Users/sgambino/build_doc/training.python_web/eggs/rjm.recipe.venv-0.8-py2.7.egg/rjm/recipe/venv/__init__.py", line 89, in install
    return f()
  File "/Users/sgambino/build_doc/training.python_web/eggs/rjm.recipe.venv-0.8-py2.7.egg/rjm/recipe/venv/__init__.py", line 89, in install
    return f()
      File "/Users/sgambino/build_doc/training.python_web/eggs/rjm.recipe.venv-0.8-py2.7.egg/rjm/recipe/venv/__init__.py", line 89, in install
subprocess.call(call_list)
    subprocess.call(call_list)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 486, in call
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 486, in call
        subprocess.call(call_list)
return func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 486, in call
KeyboardInterrupt
    dist, avail = self._satisfied(requirement)
  File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/easy_install.py", line 484, in _satisfied
        return Popen(*popenargs, **kwargs).wait()
return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1243, in wait
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1243, in wait
        return f()
return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1243, in wait
  File "/Users/sgambino/build_doc/training.python_web/eggs/rjm.recipe.venv-0.8-py2.7.egg/rjm/recipe/venv/__init__.py", line 89, in install
    subprocess.call(call_list)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 486, in call
    best_available = self._obtain(req, source)
  File "/Users/sgambino/build_doc/training.python_web/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/easy_install.py", line 639, in _obtain
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1243, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 471, in _eintr_retry_call
if index.obtain(requirement) is None:
      File "/Users/sgambino/build_doc/pyWeb/lib/python2.7/site-packages/setuptools/package_index.py", line 441, in obtain
pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 471, in _eintr_retry_call
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 471, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt    
self.find_packages(requirement)
  File "/Users/sgambino/build_doc/pyWeb/lib/python2.7/site-packages/setuptools/package_index.py", line 425, in find_packages
    return func(*args)
    return func(*args)
KeyboardInterrupt
KeyboardInterrupt
    self.scan_url(self.index_url + requirement.unsafe_name+'/')
  File "/Users/sgambino/build_doc/pyWeb/lib/python2.7/site-packages/setuptools/package_index.py", line 765, in scan_url
    self.process_url(url, True)
  File "/Users/sgambino/build_doc/pyWeb/lib/python2.7/site-packages/setuptools/package_index.py", line 324, in process_url
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 471, in _eintr_retry_call
    page = self.process_index(url, page)
  File "/Users/sgambino/build_doc/pyWeb/lib/python2.7/site-packages/setuptools/package_index.py", line 402, in process_index
    return func(*args)
    self.scan_url(new_url)
  File "/Users/sgambino/build_doc/pyWeb/lib/python2.7/site-packages/setuptools/package_index.py", line 765, in scan_url
KeyboardInterrupt
    self.process_url(url, True)
  File "/Users/sgambino/build_doc/pyWeb/lib/python2.7/site-packages/setuptools/package_index.py", line 311, in process_url
    page = f.read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 351, in read
    data = self._sock.recv(rbufsize)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 533, in read
    return self._read_chunked(amt)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 591, in _read_chunked
    value.append(self._safe_read(chunk_left))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 635, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
KeyboardInterrupt

```

**Comment by cewing** [comment]
@sgambino, thanks for the bug report.  I've updated the build system quite a bit since this report was opened, and will close this issue as soon as I can update the README to reflect the current situation.

**Comment by cewing** [comment]
The new README is now in place, and no longer uses buildout at all.  Closing as not relevant.
